# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(db_column=b'name', default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(db_column=b'borrow_date', default=datetime.datetime(2017, 12, 6, 1, 44, 35, 753229)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(db_column=b'return_date', default=datetime.datetime(2017, 12, 21, 1, 44, 35, 753257)),
        ),
    ]
